<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Professeur;

class ProfesseurSeeder extends Seeder
{
    public function run()
    {
        $professeurs = [
            [
                'user_id' => 4,
                'nom' => 'Bensalah',
                'prenom' => 'Ali',
                'rang' => 'PA',
                'statut' => 'Active',
                'is_chef_service' => true,
                'date_recrutement' => '2015-09-01',
                'specialite' => 'medicale',
                'service_id' => 1,
            ],
            [
                'user_id' => 5,
                'nom' => 'Merad',
                'prenom' => 'Sara',
                'rang' => 'PAG',
                'statut' => 'On_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2018-04-10',
                'specialite' => 'chirurgien',
                'service_id' => 2,
            ],
            [
                'user_id' => 6,
                'nom' => 'Toumi',
                'prenom' => 'Rachid',
                'rang' => 'PES',
                'statut' => 'Sick_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2013-11-15',
                'specialite' => 'medicale',
                'service_id' => 1,
            ],
            // 17 more professors
            [
                'user_id' => 24,
                'nom' => 'Kadri',
                'prenom' => 'Fatima',
                'rang' => 'PAG',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2017-03-12',
                'specialite' => 'medicale',
                'service_id' => 3,
            ],
            [
                'user_id' => 25,
                'nom' => 'Bouzid',
                'prenom' => 'Karim',
                'rang' => 'PA',
                'statut' => 'Vacation',
                'is_chef_service' => true,
                'date_recrutement' => '2014-08-22',
                'specialite' => 'chirurgien',
                'service_id' => 4,
            ],
            [
                'user_id' => 26,
                'nom' => 'Hamidi',
                'prenom' => 'Leila',
                'rang' => 'PES',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2019-01-15',
                'specialite' => 'medicale',
                'service_id' => 5,
            ],
            [
                'user_id' => 27,
                'nom' => 'Mansouri',
                'prenom' => 'Nabil',
                'rang' => 'PA',
                'statut' => 'On_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2016-07-30',
                'specialite' => 'chirurgien',
                'service_id' => 6,
            ],
            [
                'user_id' => 28,
                'nom' => 'Cherif',
                'prenom' => 'Samira',
                'rang' => 'PAG',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2018-11-05',
                'specialite' => 'medicale',
                'service_id' => 7,
            ],
            [
                'user_id' => 29,
                'nom' => 'Boukharouba',
                'prenom' => 'Youssef',
                'rang' => 'PES',
                'statut' => 'Sick_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2015-05-18',
                'specialite' => 'chirurgien',
                'service_id' => 8,
            ],
            [
                'user_id' => 30,
                'nom' => 'Saadi',
                'prenom' => 'Amel',
                'rang' => 'PA',
                'statut' => 'Active',
                'is_chef_service' => true,
                'date_recrutement' => '2013-09-10',
                'specialite' => 'medicale',
                'service_id' => 9,
            ],
            [
                'user_id' => 31,
                'nom' => 'Lounis',
                'prenom' => 'Mehdi',
                'rang' => 'PAG',
                'statut' => 'Inactive',
                'is_chef_service' => false,
                'date_recrutement' => '2017-12-01',
                'specialite' => 'chirurgien',
                'service_id' => 10,
            ],
            [
                'user_id' => 32,
                'nom' => 'Zerrouki',
                'prenom' => 'Hakim',
                'rang' => 'PES',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2020-02-14',
                'specialite' => 'medicale',
                'service_id' => 1,
            ],
            [
                'user_id' => 33,
                'nom' => 'Bendjama',
                'prenom' => 'Nadia',
                'rang' => 'PA',
                'statut' => 'On_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2014-04-25',
                'specialite' => 'chirurgien',
                'service_id' => 2,
            ],
            [
                'user_id' => 34,
                'nom' => 'Gacem',
                'prenom' => 'Rym',
                'rang' => 'PAG',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2019-06-08',
                'specialite' => 'medicale',
                'service_id' => 3,
            ],
            [
                'user_id' => 35,
                'nom' => 'Mammeri',
                'prenom' => 'Tarek',
                'rang' => 'PES',
                'statut' => 'Vacation',
                'is_chef_service' => false,
                'date_recrutement' => '2016-10-17',
                'specialite' => 'chirurgien',
                'service_id' => 4,
            ],
            [
                'user_id' => 36,
                'nom' => 'Benaissa',
                'prenom' => 'Salima',
                'rang' => 'PA',
                'statut' => 'Active',
                'is_chef_service' => true,
                'date_recrutement' => '2012-07-03',
                'specialite' => 'medicale',
                'service_id' => 5,
            ],
            [
                'user_id' => 37,
                'nom' => 'Khelifi',
                'prenom' => 'Adel',
                'rang' => 'PAG',
                'statut' => 'Sick_Leave',
                'is_chef_service' => false,
                'date_recrutement' => '2018-09-20',
                'specialite' => 'chirurgien',
                'service_id' => 6,
            ],
            [
                'user_id' => 38,
                'nom' => 'Dahmani',
                'prenom' => 'Farida',
                'rang' => 'PES',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2015-11-11',
                'specialite' => 'medicale',
                'service_id' => 7,
            ],
            [
                'user_id' => 39,
                'nom' => 'Bouchenak',
                'prenom' => 'Malik',
                'rang' => 'PA',
                'statut' => 'Inactive',
                'is_chef_service' => false,
                'date_recrutement' => '2017-02-28',
                'specialite' => 'chirurgien',
                'service_id' => 8,
            ],
            [
                'user_id' => 40,
                'nom' => 'Ait',
                'prenom' => 'Yahia',
                'rang' => 'PAG',
                'statut' => 'Active',
                'is_chef_service' => false,
                'date_recrutement' => '2020-05-15',
                'specialite' => 'medicale',
                'service_id' => 9,
            ],
        ];

        foreach ($professeurs as $prof) {
            Professeur::create($prof);
        }
    }
}